name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - master # Trigger on the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Flutter environment with a specific version
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4" # Explicitly set to your Flutter version

      # Build the Flutter web app
      - name: Build Flutter Web
        run: flutter build web --web-renderer html

      # Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
